name: tests

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build image
        run: docker build -t app .

      - name: lint
        run: docker run --rm app uv run pre-commit run -a

      - name: tests
        run: docker run --rm app uv run pytest