name: tests

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build image
        run: docker build -t app .

      - name: lint
        run: |
          docker run --rm app uv run ruff check .
          docker run --rm app uv run black --check .
          docker run --rm app uv run mypy .

      - name: tests
        run: docker run --rm app uv run pytest